name: Build

on: push

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: arduino/setup-protoc@v1
      - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
      - run: npm -g install protoc-gen-ts
      - run: go mod download
      - run: make generate
